### ISSUE TITLE
ERROR in generate_instruction.py

### ISSUE THREAD

**Issue by LeopoldACC** [tatsu-lab/stanford_alpaca#104]
Thanks for your sharing!
But when I tried the script `generate_instruction.py`, the response is not match with openai_object class. Is the openai's version not compatible? I would appreciate it if you could help me with the bug.
```
(llm) gz:/data/projects/stanford_alpaca$ python -m generate_instruction generate_instruction_following_data --output_dir ./ --num_instructions_to_generate 10  --model_name 
"text-davinci-003"                                                                                                                                                                                          
Loaded 175 human-written seed instructions                                                                                                                                                                  
prompt_batches:   0%|                                                                                                                                                                 | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/site-packages/openai/openai_object.py", line 59, in __getattr__
    return self[k]                                                                                    
KeyError: 'choices'                                                                                   
                                                                                                      
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/projects/stanford_alpaca/generate_instruction.py", line 236, in <module>
    fire.Fire(main)
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/projects/stanford_alpaca/generate_instruction.py", line 232, in main
    globals()[task](**kwargs)
  File "/data/projects/stanford_alpaca/generate_instruction.py", line 186, in generate_instruction_following_data
    results = utils.openai_completion(
  File "/data/projects/stanford_alpaca/utils.py", line 127, in openai_completion
    choices = completion_batch.choices
  File "/data/packages/anaconda3/envs/llm/lib/python3.10/site-packages/openai/openai_object.py", line 61, in __getattr__
    raise AttributeError(*err.args)
AttributeError: choices
  0%|                                                                                                                                                                                | 0/10 [00:02<?, ?it/s]
```
my openai version is 
```
Name: openai
Version: 0.27.2
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
License: 
Location: /data/packages/anaconda3/envs/llm/lib/python3.10/site-packages
Requires: aiohttp, requests, tqdm
Required-by: 
```

**Comment by LeopoldACC** [comment]
problem solved, the reason is the api key failured.
