### ISSUE TITLE
train.py doesn't work

### ISSUE THREAD

**Issue by iceja-net** [tatsu-lab/stanford_alpaca#137]
```
python3 train.py --output_dir ./model
Downloading (…)lve/main/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 651/651 [00:00<00:00, 308kB/s]
Downloading pytorch_model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████| 251M/251M [00:46<00:00, 5.36MB/s]
Downloading (…)neration_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████| 137/137 [00:00<00:00, 65.1kB/s]
Downloading (…)okenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 685/685 [00:00<00:00, 310kB/s]
Downloading (…)olve/main/vocab.json: 100%|████████████████████████████████████████████████████████████████████████████████| 899k/899k [00:00<00:00, 1.19MB/s]
Downloading (…)olve/main/merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 889kB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 441/441 [00:00<00:00, 427kB/s]
WARNING:root:Loading data...
Traceback (most recent call last):
  File "/home/katya/poligon/stanford_alpaca/train.py", line 231, in <module>
    train()
  File "/home/katya/poligon/stanford_alpaca/train.py", line 223, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
  File "/home/katya/poligon/stanford_alpaca/train.py", line 187, in make_supervised_data_module
    train_dataset = SupervisedDataset(tokenizer=tokenizer, data_path=data_args.data_path)
  File "/home/katya/poligon/stanford_alpaca/train.py", line 143, in __init__
    list_data_dict = utils.jload(data_path)
  File "/home/katya/poligon/stanford_alpaca/utils.py", line 170, in jload
    f = _make_r_io_base(f, mode)
  File "/home/katya/poligon/stanford_alpaca/utils.py", line 144, in _make_r_io_base
    f = open(f, mode=mode)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

```
cat /etc/os-release
PRETTY_NAME="KDE neon 5.27"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="5.27"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=jammy

```
```

python3 --version
Python 3.10.6

```

**Comment by surak** [comment]
Seems like you are missing some parameter on the command line. Maybe you can edit your comment and show how you loaded it?
