### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by clm971910** [tatsu-lab/stanford_alpaca#156]
![image](https://user-images.githubusercontent.com/363529/228447195-51b4dc8a-f4a2-421a-9176-831a1fa89634.png)
![image](https://user-images.githubusercontent.com/363529/228447264-0bd8f36a-6919-44bc-9a06-97d257c8ba44.png)

Traceback (most recent call last):
  File "train.py", line 25, in <module>
    import utils
  File "/home/yewang/stanford_alpaca/utils.py", line 47, in <module>
    return_text=False,
TypeError: 'type' object is not subscriptable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 144694) of binary: /home/yewang/miniconda3/envs/chatgpt/bin/python
Traceback (most recent call last):
  File "/home/yewang/miniconda3/envs/chatgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
    )(*cmd_args)
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by Quan-Sun** [comment]
from typing import Dict
dict = Dict

**Comment by clm971910** [comment]
thanks   it's work
