### ISSUE TITLE
How to run the fine-tuning using LLaMA?

### ISSUE THREAD

**Issue by 14H034160212** [tatsu-lab/stanford_alpaca#159]
Hi,

I got the following error when I run the script to fine-tune LLaMA.

```
torchrun --nproc_per_node=4 --master_port=2023 train.py \
    --model_name_or_path llama_7B_hf/llama-7b \
    --data_path ./alpaca_data.json \
    --bf16 True \
    --output_dir ./finetuned_llama_7B \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LLaMADecoderLayer' \
    --tf32 True
```

I have used the following command to convert the llama 7B weight to huggingface model.
```
python src/transformers/models/llama/convert_llama_weights_to_hf.py \
    --input_dir ../../../LLaMA/7B \
    --model_size 7B \
    --output_dir ../llama_7B_hf
```

And I got the llama 7B folder like this.
![image](https://user-images.githubusercontent.com/23516191/228808045-815c1980-fb00-4872-ac2c-a8609aae84b2.png)

Here is the full error.
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default                                                                             , to avoid your system being overloaded, please further tune the variable for op                                                                             timal performance in your application as needed.
*****************************************
/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/transform                                                                             ers/training_args.py:1356: FutureWarning: using `--fsdp_transformer_layer_cls_to                                                                             _wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
Traceback (most recent call last):
  File "/data/qbao775/stanford_alpaca/train.py", line 231, in <module>
    train()
  File "/data/qbao775/stanford_alpaca/train.py", line 196, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/transform                                                                             ers/training_args.py:1356: FutureWarning: using `--fsdp_transformer_layer_cls_to                                                                             _wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
Traceback (most recent call last):
  File "/data/qbao775/stanford_alpaca/train.py", line 231, in <module>
    train()
  File "/data/qbao775/stanford_alpaca/train.py", line 196, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/transform                                                                             ers/training_args.py:1356: FutureWarning: using `--fsdp_transformer_layer_cls_to                                                                             _wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
Traceback (most recent call last):
  File "/data/qbao775/stanford_alpaca/train.py", line 231, in <module>
    train()
  File "/data/qbao775/stanford_alpaca/train.py", line 196, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/transform                                                                             ers/training_args.py:1356: FutureWarning: using `--fsdp_transformer_layer_cls_to                                                                             _wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
Traceback (most recent call last):
  File "/data/qbao775/stanford_alpaca/train.py", line 231, in <module>
    train()
  File "/data/qbao775/stanford_alpaca/train.py", line 196, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 177030 clo                                                                             sing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_r                                                                             ank: 0 (pid: 177028) of binary: /data/qbao775/miniconda3/envs/explanation/bin/py                                                                             thon
Traceback (most recent call last):
  File "/data/qbao775/miniconda3/envs/explanation/bin/torchrun", line 8, in <mod                                                                             ule>
    sys.exit(main())
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             orch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapp                                                                             er
    return f(*args, **kwargs)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             orch/distributed/run.py", line 794, in main
    run(args)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             orch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             orch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             orch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-30_10:22:56
  host      : hgx2.novalocal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 177029)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/e                                                                             rrors.html
[2]:
  time      : 2023-03-30_10:22:56
  host      : hgx2.novalocal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 177031)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/e                                                                             rrors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-30_10:22:56
  host      : hgx2.novalocal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 177028)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/e                                                                             rrors.html
============================================================
```

Here is the package version of my environment. I follow the step using `pip install -r requirements.txt`.
```
Package                  Version
------------------------ ----------
absl-py                  1.4.0
aiohttp                  3.8.4
aiosignal                1.3.1
appdirs                  1.4.4
async-timeout            4.0.2
attrs                    22.2.0
certifi                  2022.12.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.1
docker-pycreds           0.4.0
filelock                 3.10.7
fire                     0.5.0
frozenlist               1.3.3
gitdb                    4.0.10
GitPython                3.1.31
huggingface-hub          0.13.3
idna                     3.4
Jinja2                   3.1.2
joblib                   1.2.0
lit                      16.0.0
MarkupSafe               2.1.2
mpmath                   1.3.0
multidict                6.0.4
networkx                 3.0
nltk                     3.8.1
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
openai                   0.27.2
packaging                23.0
pathtools                0.1.2
pip                      23.0.1
protobuf                 4.22.1
psutil                   5.9.4
PyYAML                   6.0
regex                    2023.3.23
requests                 2.28.2
rouge-score              0.1.2
sentencepiece            0.1.97
sentry-sdk               1.18.0
setproctitle             1.3.2
setuptools               65.6.3
six                      1.16.0
smmap                    5.0.0
sympy                    1.11.1
termcolor                2.2.0
tokenizers               0.12.1
torch                    2.0.0
tqdm                     4.65.0
transformers             4.27.4
triton                   2.0.0
typing_extensions        4.5.0
urllib3                  1.26.15
wandb                    0.14.0
wheel                    0.38.4
yarl                     1.8.2
```
I got the same error when I try to replace `--fsdp_transformer_layer_cls_to_wrap 'LLaMADecoderLayer'` to `--fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'`.

**Comment by clm971910** [comment]
same error  ,  

torchrun --nproc_per_node=1 --master_port=8888 train.py     --model_name_or_path  decapoda-research/llama-7b-hf   --data_path ./alpaca_data.json    --output_dir ./outdir/     --num_train_epochs 3     --per_device_train_batch_size 4     --per_device_eval_batch_size 4     --gradient_accumulation_steps 8     --evaluation_strategy "no"     --save_strategy "steps"     --save_steps 2000     --save_total_limit 1     --learning_rate 2e-5     --weight_decay 0.     --warmup_ratio 0.03     --lr_scheduler_type "cosine"     --logging_steps 1     --fsdp "full_shard auto_wrap"     --fsdp_transformer_layer_cls_to_wrap 'LLaMADecoderLayer'
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train()
  File "train.py", line 198, in train
    cache_dir=training_args.cache_dir,
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 439, in from_pretrained
    **kwargs,
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 873, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 579, in __getitem__
    raise KeyError(key)
KeyError: 'llama'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 241515) of binary: /home/yewang/miniconda3/envs/chatgpt/bin/python

**Comment by 14H034160212** [comment]
I solved the issue using the following command to install the transformers with `LlamaTokenizer`. My installed Transformers version is `4.28.0.dev0`.
`pip install git+https://github.com/huggingface/transformers`

Other useful links to help me run the fine-tuning for LLaMA.
[Exception: Could not find the transformer layer class to wrap in the model]
https://github.com/tatsu-lab/stanford_alpaca/issues/58#issuecomment-1472042086

Change the `tokenizer_class` as `LlamaTokenizer`.
![image](https://user-images.githubusercontent.com/23516191/228840946-e9662b62-d69e-4f6e-b7db-07a31b569361.png)

**Comment by clm971910** [comment]
pip install git+https://github.com/huggingface/transformers 

Successfully installed transformers-4.28.0.dev0

it's work  , thanks a lot

**Comment by triangle959** [comment]
pip install git+https://github.com/huggingface/transformers@fe32d793729276f6786eda4619281a328803713e
Successfully installed transformers-4.28.0.dev0

but it still has wrong:
Exception: Could not find the transformer layer class to wrap in the model.

my finetune command is 
```
torchrun --nproc_per_node=2 --master_port=20001 fastchat/train/train_mem.py ^
    --model_name_or_path D:\triangle_project\huggingface\vicuna-7b-all-v1.1  ^
    --data_path D:\triangle_project\FastChat\playground\data\Men's_Apparel_vicuna_dataset.json ^
    --output_dir output_vicuna ^
    --num_train_epochs 2 ^
    --per_device_train_batch_size 1 ^
    --per_device_eval_batch_size 1 ^
    --gradient_accumulation_steps 8 ^
    --evaluation_strategy "no" ^
    --save_strategy "steps" ^
    --save_steps 300 ^
    --save_total_limit 10 ^
    --learning_rate 2e-5 ^
    --weight_decay 0. ^
    --warmup_ratio 0.03 ^
    --lr_scheduler_type "cosine" ^
    --logging_steps 1 ^
    --fsdp "full_shard offload auto_wrap" ^
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' ^
    --model_max_length 2048 ^
    --gradient_checkpointing True ^
    --lazy_preprocess True
```

**Comment by Jerry-hyl** [comment]
@triangle959 Do you solve the problem? I have met the same issue as you after installing the transformers

**Comment by MikaSie** [comment]
@triangle959 @Jerry-hyl I have the same issue.
