### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by sanjibnarzary** [tatsu-lab/stanford_alpaca#171]
```
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    import utils
  File "./fine-tuned/stanford_alpaca/utils.py", line 40, in <module>
    prompts: Union[str, Sequence[str], Sequence[dict[str, str]], dict[str, str]],
TypeError: 'type' object is not subscriptable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3020123) of binary: /home/sn/miniconda3/envs/chatllama/bin/python
Traceback (most recent call last):
  File "/home/sn/miniconda3/envs/chatllama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sn/miniconda3/envs/chatllama/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/sn/miniconda3/envs/chatllama/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/sn/miniconda3/envs/chatllama/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/sn/miniconda3/envs/chatllama/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sn/miniconda3/envs/chatllama/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED

[TRUNCATED]
```

**Comment by MrRace** [comment]
@sanjibnarzary How to solve it ? Same problem！

**Comment by sanjibnarzary** [comment]
@MrRace 
Add Dict in line number 9 of utils.py 
```
from typing import Optional, Sequence, Union
```
```
from typing import Optional, Sequence, Union, Dict
```

and replace the line number 40 with this
```
prompts: Union[str, Sequence[str], Sequence[Dict[str, str]], Dict[str, str]],
```
