### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1

### ISSUE THREAD

**Issue by yanqiangmiffy** [tatsu-lab/stanford_alpaca#202]
ERRO:

```
Using .cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Emitting ninja build file .cache/torch_extensions/py310_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.2295243740081787 seconds
Using .cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Emitting ninja build file .cache/torch_extensions/py310_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.15020513534545898 seconds
Rank: 1 partition count [2] and sizes[(3369211904, False)] 
Rank: 0 partition count [2] and sizes[(3369211904, False)] 
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 91819 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 91820) of binary: anaconda3/envs/stanford_alpaca/bin/python
Traceback (most recent call last):
  File "anaconda3/envs/stanford_alpaca/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "anaconda3/envs/stanford_alpaca/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
train_7b_local_ds.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-11_17:06:50
  host      : worker2
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 91820)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 91820

```

deepspeed config:
```
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },

    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },

    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 1e3,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 1e3,
        "contiguous_gradients": true
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```

**Comment by yanqiangmiffy** [comment]
args:

```
args = [
    "--report_to=none",
    "--model_name_or_path=pretrained_models/llama-7b-hf",
    "--data_path=alpaca_data.json",
    # "--bf16=True",
    "--output_dir=./output",
    "--cache_dir=./cache",
    "--num_train_epochs=3",
    "--per_device_train_batch_size=2",
    "--per_device_eval_batch_size=2",
    "--gradient_accumulation_steps=4",
    "--evaluation_strategy=no",
    "--save_strategy=steps",
    "--save_steps=1000",
    "--save_total_limit=1",
    "--learning_rate=2e-5",
    "--weight_decay=0.",
    "--warmup_ratio=0.03",
    "--lr_scheduler_type=cosine",
    "--report_to=tensorboard",
    "--gradient_checkpointing=True",
    # "--fsdp=full_shard auto_wrap",
    # "--fsdp_transformer_layer_cls_to_wrap=LLaMADecoderLayer",
    # "--tf32=True",
    "--fp16=True",
    "--deepspeed=deepspeed-cfg/zero2.json"
]
```

**Comment by yanqiangmiffy** [comment]
CPU:ram 128g，is it not enough？
GPU:A100*80g x2, torchrun --nproc_per_node=2 train_7b_local_ds.py
