### ISSUE TITLE
what is the evaluation_strategy and how to use it?

### ISSUE THREAD

**Issue by 14H034160212** [tatsu-lab/stanford_alpaca#214]
Hi,

I got one question, I have seen the `evaluation_strategy` in the [training script](https://github.com/tatsu-lab/stanford_alpaca#fine-tuning). But I do not know the meaning for that parameter? Does that mean if I set `evaluation_strategy` as yes, I will use the evaluation during the training process? Thanks in advance.

**Comment by 14H034160212** [comment]
It can be selected as `no`, `steps` and `epoch` for the evaluation.

**Comment by 14H034160212** [comment]
Does the `--evaluation_strategy "steps"` not working? I set this parameter and then I got the following error. 

```
Traceback (most recent call last):
  File "/data/qbao775/Explanation-Generation/train.py", line 231, in <module>
Traceback (most recent call last):
  File "/data/qbao775/Explanation-Generation/train.py", line 231, in <module>
    train()
  File "/data/qbao775/Explanation-Generation/train.py", line 225, in train
Traceback (most recent call last):
  File "/data/qbao775/Explanation-Generation/train.py", line 231, in <module>
    train()
  File "/data/qbao775/Explanation-Generation/train.py", line 225, in train
    trainer.train()
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1639, in train
    trainer.train()
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1639, in train
                                                                                                                                                                 train()
  File "/data/qbao775/Explanation-Generation/train.py", line 225, in train
    return inner_training_loop(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1983, in _inner_training_loop
    trainer.train()
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1983, in _inner_training_loop
{'loss': 2.5876, 'learning_rate': 5.000000000000001e-07, 'epoch': 0.0}
  0%|                                        | 1/1310 [00:06<2:12:42,  6.08s/it]                                                                                 self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_                                                                             eval)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2240, in _maybe_log_save_evaluate
        self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_                                                                             for_eval)return inner_training_loop(

  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2240, in _maybe_log_save_evaluate
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1983, in _inner_training_loop
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2935, in evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2935, in evaluate
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_                                                                             eval)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2240, in _maybe_log_save_evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 939, in get_eval_dataloader
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2935, in evaluate
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 939, in get_eval_dataloader
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 939, in get_eval_dataloader
Traceback (most recent call last):
  File "/data/qbao775/Explanation-Generation/train.py", line 231, in <module>
    train()
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
  File "/data/qbao775/Explanation-Generation/train.py", line 225, in train
    trainer.train()
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 1983, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_                                                                             eval)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2240, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 2935, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/data/qbao775/miniconda3/envs/explanation/lib/python3.10/site-packages/t                                                                             ransformers/trainer.py", line 939, in get_eval_dataloader
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
```
