### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by WYXG233** [tatsu-lab/stanford_alpaca#287]
I'm trying to train the alpaca model using python 3.10. But when I try to train, there is always a bug here:
```Traceback (most recent call last):
  File "./stanford_alpaca/weight_diff.py", line 21, in <module>
    from train import smart_tokenizer_and_embedding_resize
  File "./stanford_alpaca/train.py", line 22, in <module>
    import utils
  File "./stanford_alpaca/utils.py", line 40, in <module>
    prompts: Union[str, Sequence[str], Sequence[dict[str, str]], dict[str, str]],
TypeError: 'type' object is not subscriptable
```

**Comment by dongguanting** [comment]
same problem

**Comment by zhangyx0417** [comment]
the same

**Comment by zhangyx0417** [comment]
> zhangyx0417

see #171

**Comment by zhangyx0417** [comment]
#171
