### ISSUE TITLE
No checkpoint and no eval_dataset

### ISSUE THREAD

**Issue by kriskrisliu** [tatsu-lab/stanford_alpaca#42]
It seems no eval_dataset and thus no storing for checkpoint ?

(for privacy, I hide the absolute file path and replace with <path>)
```
Traceback (most recent call last):
  File "<path>/stanford_alpaca/train.py", line 232, in <module>
    train()
  File "<path>/stanford_alpaca/train.py", line 226, in train
    trainer.evaluate()
  File "<path>/stanford_alpaca/transformers-68d640f7c368bcaaaecfc678f11908ebbd3d6176/src/transformers/trainer.py", line 2920, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "<path>/stanford_alpaca/transformers-68d640f7c368bcaaaecfc678f11908ebbd3d6176/src/transformers/trainer.py", line 934, in get_eval_dataloader
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
```

**Comment by kriskrisliu** [comment]
after deleting `trainer.evaluate()` in train.py, everything is ok
