### ISSUE TITLE
No evaluation dataset was given for the trainer

### ISSUE THREAD

**Issue by XuhuiRen** [tatsu-lab/stanford_alpaca#50]
Hi, there, I just finish the finetuning process as introduced in train.py. However, I encountered one problem about trainer.evaluate().
```log
{'loss': 0.3974, 'learning_rate': 3.5380966993958655e-11, 'epoch': 3.0}
{'loss': 0.4492, 'learning_rate': 0.0, 'epoch': 3.0}
{'train_runtime': 17758.138, 'train_samples_per_second': 8.785, 'train_steps_per_second': 0.069, 'train_loss': 0.7304400721402787, 'epoch': 3.0}
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1218/1218 [4:55:48<00:00, 14.57s/it]
Traceback (most recent call last):
  File "/home/codes/finetune_llama/alpaca/train.py", line 233, in <module>
    train()
  File "/home/codes/finetune_llama/alpaca/train.py", line 227, in train
    trainer.evaluate()
  File "/home/anaconda3/envs/hawq/lib/python3.9/site-packages/transformers/trainer.py", line 2920, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/home/anaconda3/envs/hawq/lib/python3.9/site-packages/transformers/trainer.py", line 934, in get_eval_dataloader
    raise ValueError("Trainer: evaluation requires an eval_dataset.")
ValueError: Trainer: evaluation requires an eval_dataset.
```

Should I give an eval_dataset here?

**Comment by puyuanliu** [comment]
Thanks for the reply! Unfortunately no, it looks like the checkpoint is
saved after trainer.evaluate().

KurtFeynmanGodel ***@***.***> 于 2023年3月16日周四 08:19写道：

**Comment by charliezjw** [comment]
Got the same error.
