### ISSUE TITLE
Exception: Could not find the transformer layer class to wrap in the model.

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [tatsu-lab/stanford_alpaca#94]
Traceback (most recent call last):
  File "/root/train.py", line 231, in <module>
    train()
  File "/root/train.py", line 225, in train
    trainer.train()
  File "/root/anaconda3/envs/test/lib/python3.10/site-packages/transformers/trainer.py", line 1628, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/test/lib/python3.10/site-packages/transformers/trainer.py", line 1715, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/root/anaconda3/envs/test/lib/python3.10/site-packages/transformers/trainer.py", line 1442, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.

transformers installed from https://github.com/huggingface/transformers/pull/21955

**Comment by Vivecccccc** [comment]
same issue here

**Comment by Vivecccccc** [comment]
wonder if you could execute these two with python which is instructed by https://github.com/huggingface/transformers/pull/21955
```
tokenizer = transformers.LLaMATokenizer.from_pretrained("/output/path/tokenizer/")
model = transformers.LLaMAForCausalLM.from_pretrained("/output/path/llama-7b/")
```
I discovered that I couldn't, so I consider it might be due to the installation of that forked transformers...

**Comment by Vivecccccc** [comment]
Found possible solution here https://github.com/tatsu-lab/stanford_alpaca/issues/58#issuecomment-1472042086

**Comment by qizzzh** [comment]
I hit the same error and that solution doesn't work because I'm already using `LlamaDecoderLayer` 
```
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train()
  File "train.py", line 225, in train
    trainer.train()
  File "/home/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1636, in train
    return inner_training_loop(
  File "/home//.local/lib/python3.8/site-packages/transformers/trainer.py", line 1723, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
  File "/home/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1443, in _wrap_model
    raise Exception("Could not find the transformer layer class to wrap in the model.")
```
